-- ������ ����
DROP SEQUENCE SEQ_COMMENT_CODE;
DROP SEQUENCE SEQ_NOTE_CODE;
DROP SEQUENCE SEQ_BOARD_CODE;
DROP SEQUENCE SEQ_MENU_CODE;
DROP SEQUENCE SEQ_COMPANY_CODE;
DROP SEQUENCE SEQ_RANK_CODE;
DROP SEQUENCE SEQ_DEPT_CODE;
DROP SEQUENCE SEQ_ICECREAM_CODE;
DROP SEQUENCE SEQ_IN_OUT_CODE;
DROP SEQUENCE SEQ_ADDENDUM_CODE;
DROP SEQUENCE SEQ_EA_CODE;
DROP SEQUENCE SEQ_DOCUMENT_CODE;
DROP SEQUENCE SEQ_EA_PATH_CODE;
DROP SEQUENCE SEQ_VOTE_CODE;
DROP SEQUENCE SEQ_SP_CODE;
DROP SEQUENCE SEQ_SALARY_CODE;

CREATE SEQUENCE SEQ_COMMENT_CODE
START WITH 1;
CREATE SEQUENCE SEQ_NOTE_CODE
START WITH 1;
CREATE SEQUENCE SEQ_BOARD_CODE
START WITH 1;
CREATE SEQUENCE SEQ_MENU_CODE
START WITH 1;
CREATE SEQUENCE SEQ_COMPANY_CODE
START WITH 1;
CREATE SEQUENCE SEQ_RANK_CODE
START WITH 1;
CREATE SEQUENCE SEQ_DEPT_CODE
START WITH 1;
CREATE SEQUENCE SEQ_ICECREAM_CODE
START WITH 1;
CREATE SEQUENCE SEQ_IN_OUT_CODE
START WITH 1;
CREATE SEQUENCE SEQ_ADDENDUM_CODE
START WITH 1;
CREATE SEQUENCE SEQ_EA_CODE
START WITH 1;
CREATE SEQUENCE SEQ_DOCUMENT_CODE
START WITH 1;
CREATE SEQUENCE SEQ_EA_PATH_CODE
START WITH 1;
CREATE SEQUENCE SEQ_VOTE_CODE
START WITH 1;
CREATE SEQUENCE SEQ_SP_CODE
START WITH 1;
CREATE SEQUENCE SEQ_SALARY_CODE
START WITH 1;

-- �Խ��� ���̺�
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"REPORTING_DATE"	DATE		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(255)		NOT NULL,
	"BOARD_HITS"	NUMBER		NOT NULL,
	"BOARD_CATEGORY"	NUMBER		NOT NULL,
    CONSTRAINT UK_BOARD_CATEGORY CHECK(BOARD_CATEGORY IN ('1', '2'))
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '�Խ��� ��ȣ';
COMMENT ON COLUMN "BOARD"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '����';
COMMENT ON COLUMN "BOARD"."REPORTING_DATE" IS '�ۼ���';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '����';
COMMENT ON COLUMN "BOARD"."BOARD_HITS" IS '��ȸ��';
COMMENT ON COLUMN "BOARD"."BOARD_CATEGORY" IS 'ī�װ�(1 : ��������, 2 : �系�Խ���)';

-- ��� ���� ���̺�
DROP TABLE "INVENTORY" CASCADE CONSTRAINTS;
CREATE TABLE "INVENTORY" (
	"ICE_NO"	NUMBER		NOT NULL,
	"CO_SERIAL_NO"	NUMBER		NOT NULL,
	"INVEN_REMAIN_STOCK"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "INVENTORY"."ICE_NO" IS '���̽�ũ�� ��ȣ';
COMMENT ON COLUMN "INVENTORY"."CO_SERIAL_NO" IS 'ȸ�� �Ϸ� ��ȣ';
COMMENT ON COLUMN "INVENTORY"."INVEN_REMAIN_STOCK" IS '���� ���';

-- ���� ���̺�
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
CREATE TABLE "MEMBER" (
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"CO_SERIAL_NO"	NUMBER		NOT NULL,
	"DEPT_NO"	NUMBER		NOT NULL,
	"RANK_NO"	NUMBER		NOT NULL,
    MEMBER_PWD VARCHAR2(255) NOT NULL,
	"MEMBER_EMP_NO"	NUMBER		NOT NULL,
	"MEMBER_BIRTH"	VARCHAR2(255)		NOT NULL,
	"MEMBER_PHONE_NO"	VARCHAR2(255)		NOT NULL,
	"MEMBER_JOIN_DATE"	DATE		NOT NULL,
	"MEMBER_QUIT_DATE"	DATE		NULL,
	"MEMBER_REGULAR_PAY"	NUMBER		NOT NULL,
	"MEMBER_BONUS"	NUMBER		NOT NULL,
	"MEMBER_ANNUAL_INCOME"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(255)		NOT NULL,
    "ENT_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT UK_ENT_YN CHECK("ENT_YN" IN ('Y', 'N'))
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "MEMBER"."CO_SERIAL_NO" IS 'ȸ�� �Ϸ� ��ȣ';
COMMENT ON COLUMN "MEMBER"."DEPT_NO" IS '�μ� ��ȣ';
COMMENT ON COLUMN "MEMBER"."RANK_NO" IS '���޹�ȣ';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMP_NO" IS '���';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '�������';
COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE_NO" IS '��ȭ��ȣ';
COMMENT ON COLUMN "MEMBER"."MEMBER_JOIN_DATE" IS '�Ի���';
COMMENT ON COLUMN "MEMBER"."MEMBER_QUIT_DATE" IS '�����';
COMMENT ON COLUMN "MEMBER"."MEMBER_REGULAR_PAY" IS '�⺻��';
COMMENT ON COLUMN "MEMBER"."MEMBER_BONUS" IS '���ʽ�';
COMMENT ON COLUMN "MEMBER"."MEMBER_ANNUAL_INCOME" IS '����';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '�̸���';
COMMENT ON COLUMN "MEMBER".MEMBER_PWD IS '��й�ȣ';
COMMENT ON COLUMN "MEMBER".ENT_YN IS '��������';

-- ���� ���� ���̺�
DROP TABLE "TNA" CASCADE CONSTRAINTS;
CREATE TABLE "TNA" (
	"TNA_DATE"	DATE		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"TNA_CODE"	NUMBER		NULL,
    CONSTRAINT UK_TNA_CODE CHECK(TNA_CODE IN ('1', '2', '3', '4'))
);

COMMENT ON COLUMN "TNA"."TNA_DATE" IS '��¥';
COMMENT ON COLUMN "TNA"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "TNA"."TNA_CODE" IS '�����ڵ�(1 : ����, 2 : ����, 3 : ����, 4 : ���)';

-- ���� ���̺�
DROP TABLE "NOTE" CASCADE CONSTRAINTS;
CREATE TABLE "NOTE" (
	"NOTE_SERIAL_NO"	NUMBER		NOT NULL,
	"SENT_MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"RECEIVE_MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"NOTE_SEND_DATE"	DATE		NOT NULL,
	"NOTE_RECEPTION"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"NOTE_CONTENT"	CLOB		NOT NULL,
    CONSTRAINT UK_NOTE_RECEPTION CHECK("NOTE_RECEPTION" IN ('Y', 'N'))
);

COMMENT ON COLUMN "NOTE"."NOTE_SERIAL_NO" IS '���� �Ϸù�ȣ';
COMMENT ON COLUMN "NOTE"."SENT_MEMBER_NAME" IS '�߽���';
COMMENT ON COLUMN "NOTE"."RECEIVE_MEMBER_NAME" IS '������';
COMMENT ON COLUMN "NOTE"."NOTE_SEND_DATE" IS '�߽���';
COMMENT ON COLUMN "NOTE"."NOTE_RECEPTION" IS '���Ż���';
COMMENT ON COLUMN "NOTE"."NOTE_CONTENT" IS '����';

-- ���� ���� ���̺�
DROP TABLE "ELECTRONIC_APPROVAL" CASCADE CONSTRAINTS;
CREATE TABLE "ELECTRONIC_APPROVAL" (
	"EA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"EA_DATE"	DATE		NOT NULL,
	"EA_TITLE"	VARCHAR2(255)		NOT NULL,
	"EA_CONTENT"	CLOB		NOT NULL,
	"EA_CATEGORY"	NUMBER		NOT NULL,
	"EA_SAVENUM"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_SERIAL_NO" IS '��ȼ� �Ϸù�ȣ';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_DATE" IS '�ۼ�����';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_TITLE" IS '��ȼ� ����';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_CONTENT" IS '���� ����';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_CATEGORY" IS '���� ī�װ�';
COMMENT ON COLUMN "ELECTRONIC_APPROVAL"."EA_SAVENUM" IS '���� ���� ����';

-- �ް��� ���̺�
DROP TABLE "LEAVE_APPLICATION" CASCADE CONSTRAINTS;
CREATE TABLE "LEAVE_APPLICATION" (
	"LA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"LA_REPORTING_DATE"	DATE		NOT NULL,
	"LA_DEPT_NAME"	VARCHAR2(30)		NOT NULL,
	"LA_TYPE"	VARCHAR2(50)		NOT NULL,
	"LA_HOLIDAY"	DATE		NOT NULL,
	"LA_REASON"	CLOB		NOT NULL,
	"LA_PROXY"	VARCHAR2(30)		NOT NULL,
	"LA_COMMENT"	VARCHAR2(255)		NULL,
	"LA_APPROVAL"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_SERIAL_NO" IS '�ް��� �Ϸù�ȣ';
COMMENT ON COLUMN "LEAVE_APPLICATION"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_REPORTING_DATE" IS '��û����';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_DEPT_NAME" IS '�μ���';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_TYPE" IS '�ް� ����';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_HOLIDAY" IS '�ް� �Ⱓ';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_REASON" IS '�ް� ����';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_PROXY" IS '�븮 ������';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_COMMENT" IS '÷��';
COMMENT ON COLUMN "LEAVE_APPLICATION"."LA_APPROVAL" IS '�������';

-- ��ǥ ���̺�
DROP TABLE "VOTE" CASCADE CONSTRAINTS;
CREATE TABLE "VOTE" (
	"VOTE_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"VOTE_TITLE"	VARCHAR2(250)		NOT NULL,
	"VOTE_CONTENT"	CLOB		NOT NULL,
	"VOTE_CATEGORY_NO"	NUMBER		NOT NULL,
	"VOTE_REG_DATE"	DATE		NOT NULL,
	"VOTE_END_DATE"	DATE		NOT NULL,
	"VOTE_HIT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "VOTE"."VOTE_SERIAL_NO" IS '��ǥ ��ȣ';
COMMENT ON COLUMN "VOTE"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "VOTE"."VOTE_TITLE" IS '��ǥ Ÿ��Ʋ';
COMMENT ON COLUMN "VOTE"."VOTE_CONTENT" IS '��ǥ ����';
COMMENT ON COLUMN "VOTE"."VOTE_CATEGORY_NO" IS '��ǥ ī�װ� ��ȣ';
COMMENT ON COLUMN "VOTE"."VOTE_REG_DATE" IS '��ǥ �������';
COMMENT ON COLUMN "VOTE"."VOTE_END_DATE" IS '��ǥ ��������';
COMMENT ON COLUMN "VOTE"."VOTE_HIT" IS '��ǥ ��ȸ��';

-- ��� ���̺�
DROP TABLE "COMMENTS" CASCADE CONSTRAINTS;
CREATE TABLE "COMMENTS" (
	"COMMENTS_NO"	NUMBER		NOT NULL,
	"REF_COMMENTS_NO"	NUMBER NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"COMMENTS_CONTENT"	CLOB		NOT NULL,
	"COMMENTS_DATE"	DATE		NOT NULL,
	"COMMENTS_DEPTH"	NUMBER		NOT NULL,
	"COMMENTS_LENGTH"	NUMBER		NOT NULL,
	"COMMENTS_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
    CONSTRAINT UK_COMMENTS_STATUS CHECK("COMMENTS_STATUS" IN ('Y', 'N'))
);

COMMENT ON COLUMN "COMMENTS"."COMMENTS_NO" IS '��� ��ȣ';
COMMENT ON COLUMN "COMMENTS"."REF_COMMENTS_NO" IS '���� ��ȣ';
COMMENT ON COLUMN "COMMENTS"."BOARD_NO" IS '�Խ��� ��ȣ';
COMMENT ON COLUMN "COMMENTS"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "COMMENTS"."COMMENTS_CONTENT" IS '����';
COMMENT ON COLUMN "COMMENTS"."COMMENTS_DATE" IS '�ۼ���';
COMMENT ON COLUMN "COMMENTS"."COMMENTS_DEPTH" IS '��� ����';
COMMENT ON COLUMN "COMMENTS"."COMMENTS_LENGTH" IS '��� ����';
COMMENT ON COLUMN "COMMENTS"."COMMENTS_STATUS" IS '��� ����';

-- ���̽�ũ�� ���̺�
DROP TABLE "ICECREAM" CASCADE CONSTRAINTS;
CREATE TABLE "ICECREAM" (
	"ICE_NO"	NUMBER		NOT NULL,
	"ICE_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "ICECREAM"."ICE_NO" IS '���̽�ũ�� ��ȣ';
COMMENT ON COLUMN "ICECREAM"."ICE_NAME" IS '���̽�ũ�� �̸�';

-- ȸ�� ���̺�
DROP TABLE "COMPANY" CASCADE CONSTRAINTS;
CREATE TABLE "COMPANY" (
	"CO_SERIAL_NO"	NUMBER		NOT NULL,
	"CO_DIVISION"	VARCHAR2(255)		NOT NULL,
	"CO_NAME"	VARCHAR2(255)		NOT NULL,
	"CO_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
    CONSTRAINT UK_CO_STATUS CHECK("CO_STATUS" IN ('Y', 'N'))
);

COMMENT ON COLUMN "COMPANY"."CO_SERIAL_NO" IS 'ȸ�� �Ϸ� ��ȣ';
COMMENT ON COLUMN "COMPANY"."CO_DIVISION" IS 'ȸ�� ����';
COMMENT ON COLUMN "COMPANY"."CO_NAME" IS 'ȸ���';
COMMENT ON COLUMN "COMPANY"."CO_STATUS" IS '� ����';

-- �ް��� ������� ���̺�
DROP TABLE "LA_APPROVAL_PATH" CASCADE CONSTRAINTS;
CREATE TABLE "LA_APPROVAL_PATH" (
	"LA_TURN"	NUMBER		NOT NULL,
	"LA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"LA_STATUS"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LA_APPROVAL_PATH"."LA_TURN" IS '�ް��� ����';
COMMENT ON COLUMN "LA_APPROVAL_PATH"."LA_SERIAL_NO" IS '�ް��� �Ϸù�ȣ';
COMMENT ON COLUMN "LA_APPROVAL_PATH"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "LA_APPROVAL_PATH"."LA_STATUS" IS '�������';

-- �μ� ���̺�
DROP TABLE "DEPT" CASCADE CONSTRAINTS;
CREATE TABLE "DEPT" (
	"DEPT_NO"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "DEPT"."DEPT_NO" IS '�μ� ��ȣ';
COMMENT ON COLUMN "DEPT"."DEPT_NAME" IS '�μ���';

-- ���� ���̺�
DROP TABLE "RANK" CASCADE CONSTRAINTS;
CREATE TABLE "RANK" (
	"RANK_NO"	NUMBER		NOT NULL,
	"RANK_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "RANK"."RANK_NO" IS '���޹�ȣ';
COMMENT ON COLUMN "RANK"."RANK_NAME" IS '���޸�';

-- ���� ���� ÷�� ���̺�
DROP TABLE "ADDENDUM" CASCADE CONSTRAINTS;
CREATE TABLE "ADDENDUM" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"REF_COMMENT_NO"	NUMBER	NULL,
	"EA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"COMMENT_CONTENT"	CLOB		NOT NULL,
	"COMMENT_DATE"	DATE		NOT NULL,
	"COMMENT_DEPTH"	NUMBER		NOT NULL,
	"COMMENT_LENGTH"	NUMBER		NOT NULL,
	"COMMENT_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
    CONSTRAINT UK_COMMENT_YN CHECK("COMMENT_YN" IN ('Y', 'N'))
);

COMMENT ON COLUMN "ADDENDUM"."COMMENT_NO" IS '÷�� ��ȣ';
COMMENT ON COLUMN "ADDENDUM"."REF_COMMENT_NO" IS '���� ÷�� ��ȣ';
COMMENT ON COLUMN "ADDENDUM"."EA_SERIAL_NO" IS '��ȼ� �Ϸù�ȣ';
COMMENT ON COLUMN "ADDENDUM"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "ADDENDUM"."COMMENT_CONTENT" IS '����';
COMMENT ON COLUMN "ADDENDUM"."COMMENT_DATE" IS '�ۼ���';
COMMENT ON COLUMN "ADDENDUM"."COMMENT_DEPTH" IS '÷�� ����';
COMMENT ON COLUMN "ADDENDUM"."COMMENT_LENGTH" IS '÷�� ����';
COMMENT ON COLUMN "ADDENDUM"."COMMENT_YN" IS '��� ����';

-- ���� ���� ������ ���̺�
DROP TABLE "EA_CARBON" CASCADE CONSTRAINTS;
CREATE TABLE "EA_CARBON" (
	"EA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"EA_CC_REFERENCE_STATE"	NUMBER	NOT NULL
);

COMMENT ON COLUMN "EA_CARBON"."EA_SERIAL_NO" IS '��ȼ� �Ϸù�ȣ';
COMMENT ON COLUMN "EA_CARBON"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "EA_CARBON"."EA_CC_REFERENCE_STATE" IS '��������';

-- �ް��� ÷�� ���̺�
DROP TABLE "LA_ADDENDUM" CASCADE CONSTRAINTS;
CREATE TABLE "LA_ADDENDUM" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"REF_COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"LA_SERIAL_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	CLOB		NOT NULL,
	"COMMENT_DATE"	DATE		NOT NULL,
	"COMMENT_DEPTH"	NUMBER		NOT NULL,
	"COMMENT_LENGTH"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LA_ADDENDUM"."COMMENT_NO" IS '��� ��ȣ';
COMMENT ON COLUMN "LA_ADDENDUM"."REF_COMMENT_NO" IS '��� ��ȣ';
COMMENT ON COLUMN "LA_ADDENDUM"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "LA_ADDENDUM"."LA_SERIAL_NO" IS '�ް��� �Ϸù�ȣ';
COMMENT ON COLUMN "LA_ADDENDUM"."COMMENT_CONTENT" IS '����';
COMMENT ON COLUMN "LA_ADDENDUM"."COMMENT_DATE" IS '�ۼ���';
COMMENT ON COLUMN "LA_ADDENDUM"."COMMENT_DEPTH" IS '��� ����';
COMMENT ON COLUMN "LA_ADDENDUM"."COMMENT_LENGTH" IS '��� ����';

-- ���� ��� ���̺�
DROP TABLE "DOCUMENT_FORM" CASCADE CONSTRAINTS;
CREATE TABLE "DOCUMENT_FORM" (
	"DF_NO"	NUMBER		NOT NULL,
	"DF_FORM"	CLOB		NOT NULL
);

COMMENT ON COLUMN "DOCUMENT_FORM"."DF_NO" IS '��� ��ȣ';
COMMENT ON COLUMN "DOCUMENT_FORM"."DF_FORM" IS '����';

-- ��ǥ ������ ���̺�
DROP TABLE "VOTE_OPTION" CASCADE CONSTRAINTS;
CREATE TABLE "VOTE_OPTION" (
	"VOTE_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"VOTE_DESC"	VARCHAR2(255)		NOT NULL,
	"NUMBER_VOTE"	NUMBER		NULL
);

COMMENT ON COLUMN "VOTE_OPTION"."VOTE_SERIAL_NO" IS '��ǥ ��ȣ';
COMMENT ON COLUMN "VOTE_OPTION"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "VOTE_OPTION"."VOTE_DESC" IS '������ ����';
COMMENT ON COLUMN "VOTE_OPTION"."NUMBER_VOTE" IS '��ǥ��';

-- ����� ���� ���̺�
DROP TABLE "IN_OUT" CASCADE CONSTRAINTS;
CREATE TABLE "IN_OUT" (
	"IN_OUT_NO"	NUMBER		NOT NULL,
	"ICE_NO"	NUMBER		NOT NULL,
	"CO_SERIAL_NO"	NUMBER		NOT NULL,
	"IN_OUT_DATE"	DATE		NOT NULL,
	"IN_OUT_DIVISION"	NUMBER		NOT NULL,
	"IN_OUT_AMOUNT"	NUMBER		NOT NULL,
    CONSTRAINT UK_IN_OUT_DIVISION CHECK(IN_OUT_DIVISION IN ('1', '2', '3'))
);

COMMENT ON COLUMN "IN_OUT"."IN_OUT_NO" IS '����� ������ȣ';
COMMENT ON COLUMN "IN_OUT"."ICE_NO" IS '���̽�ũ�� ��ȣ';
COMMENT ON COLUMN "IN_OUT"."CO_SERIAL_NO" IS 'ȸ�� �Ϸ� ��ȣ';
COMMENT ON COLUMN "IN_OUT"."IN_OUT_DATE" IS '����� ����';
COMMENT ON COLUMN "IN_OUT"."IN_OUT_DIVISION" IS '����� ����(1 : �԰�, 2 : ���, 3 : �Ǹ�)';
COMMENT ON COLUMN "IN_OUT"."IN_OUT_AMOUNT" IS '����';

-- ȸ���� ���� ���̺�
DROP TABLE "MEMBER_ROLE" CASCADE CONSTRAINTS;
CREATE TABLE "MEMBER_ROLE" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_ROLE"."AUTHORITY_CODE" IS '�����ڵ�';
COMMENT ON COLUMN "MEMBER_ROLE"."MEMBER_NAME" IS '�����';

-- ���� ���̺�
DROP TABLE "AUTHORITY" CASCADE CONSTRAINTS;
CREATE TABLE "AUTHORITY" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"AUTHORITY_NAME"	VARCHAR2(255)		NOT NULL,
	"AUTHORITY_DESC"	VARCHAR2(4000)		NOT NULL
);

COMMENT ON COLUMN "AUTHORITY"."AUTHORITY_CODE" IS '�����ڵ�';
COMMENT ON COLUMN "AUTHORITY"."AUTHORITY_NAME" IS '���Ѹ�';
COMMENT ON COLUMN "AUTHORITY"."AUTHORITY_DESC" IS '���Ѽ���';

-- ���Ѻ����ٰ��ɸ޴� ���̺�
DROP TABLE "AUTHENTICATED_MENU" CASCADE CONSTRAINTS;
CREATE TABLE "AUTHENTICATED_MENU" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"MENU_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "AUTHENTICATED_MENU"."AUTHORITY_CODE" IS '�����ڵ�';
COMMENT ON COLUMN "AUTHENTICATED_MENU"."MENU_CODE" IS '�޴��ڵ�';

-- ����޴� ���̺�
DROP TABLE "GLOBAL_MENU" CASCADE CONSTRAINTS;
CREATE TABLE "GLOBAL_MENU" (
	"MENU_CODE"	NUMBER		NOT NULL,
	"REF_MENU_CODE"	NUMBER		NOT NULL,
	"MENU_NAME"	VARCHAR2(255)		NOT NULL,
	"MENU_URL"	VARCHAR2(255)		NOT NULL,
	"MENU_DESC"	VARCHAR2(4000)		NULL,
	"MENU_ORDER"	NUMBER		NOT NULL,
	"REMOVED_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"MENU_TYPE"	NUMBER		NOT NULL,
    CONSTRAINT UK_REMOVED_YN CHECK(REMOVED_YN IN ('Y', 'N'))
);

COMMENT ON COLUMN "GLOBAL_MENU"."MENU_CODE" IS '�޴��ڵ�';
COMMENT ON COLUMN "GLOBAL_MENU"."REF_MENU_CODE" IS '�����޴��ڵ�';
COMMENT ON COLUMN "GLOBAL_MENU"."MENU_NAME" IS '�޴���';
COMMENT ON COLUMN "GLOBAL_MENU"."MENU_URL" IS '�޴�URL';
COMMENT ON COLUMN "GLOBAL_MENU"."MENU_DESC" IS '�޴�����';
COMMENT ON COLUMN "GLOBAL_MENU"."MENU_ORDER" IS '��¼���';
COMMENT ON COLUMN "GLOBAL_MENU"."REMOVED_YN" IS '��������';
COMMENT ON COLUMN "GLOBAL_MENU"."MENU_TYPE" IS '����';

-- ���� ���� ���� ���� ���̺�
DROP TABLE "EA_APPROVAL_PATH" CASCADE CONSTRAINTS;
CREATE TABLE "EA_APPROVAL_PATH" (
	"EA_NO"	NUMBER		NOT NULL,
	"EA_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"EA_STATUS"	NUMBER		NOT NULL,
    CONSTRAINT UK_EA_STATUS CHECK(EA_STATUS IN ('1', '2', '3', '4'))
);

COMMENT ON COLUMN "EA_APPROVAL_PATH"."EA_NO" IS '���� ���� ����';
COMMENT ON COLUMN "EA_APPROVAL_PATH"."EA_SERIAL_NO" IS '��ȼ� �Ϸù�ȣ';
COMMENT ON COLUMN "EA_APPROVAL_PATH"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "EA_APPROVAL_PATH"."EA_STATUS" IS '���� ����(1 : ������, 2 : ����ݷ�, 3: ����, 4 : �������)';

-- ��ǥ ���� ���̺�
DROP TABLE "VOTE_PARTICIPATION" CASCADE CONSTRAINTS;
CREATE TABLE "VOTE_PARTICIPATION" (
	"VOTE_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL
);

COMMENT ON COLUMN "VOTE_PARTICIPATION"."VOTE_SERIAL_NO" IS '��ǥ ��ȣ';
COMMENT ON COLUMN "VOTE_PARTICIPATION"."MEMBER_NAME" IS '�����';

-- ������ ���� ���̺�
DROP TABLE "SP_MANAGEMENT" CASCADE CONSTRAINTS;
CREATE TABLE "SP_MANAGEMENT" (
    SP_NO   NUMBER NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"SERVERANCE_PAY"	NUMBER		NOT NULL,
	"EMP_YEAR"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SP_MANAGEMENT".SP_NO IS '�����ݹ�ȣ';
COMMENT ON COLUMN "SP_MANAGEMENT"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "SP_MANAGEMENT"."SERVERANCE_PAY" IS '������';
COMMENT ON COLUMN "SP_MANAGEMENT"."EMP_YEAR" IS '�������';

-- �޿� ���̺�
DROP TABLE "SALARY" CASCADE CONSTRAINTS;
CREATE TABLE "SALARY" (
	"SAL_SERIAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"SAL_DATE"	DATE		NOT NULL,
	"SAL_REGULAR_PAY"	NUMBER		NULL,
	"SAL_BONUS"	NUMBER		NULL
);

COMMENT ON COLUMN "SALARY"."SAL_SERIAL_NO" IS '�޿� �Ϸù�ȣ';
COMMENT ON COLUMN "SALARY"."MEMBER_NAME" IS '�����';
COMMENT ON COLUMN "SALARY"."SAL_DATE" IS '�ͼӿ���';
COMMENT ON COLUMN "SALARY"."SAL_REGULAR_PAY" IS '���� �ݾ�';
COMMENT ON COLUMN "SALARY"."SAL_BONUS" IS '���ʽ� �ݾ�';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "INVENTORY" ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY (
	"ICE_NO",
	"CO_SERIAL_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NAME"
);

ALTER TABLE "TNA" ADD CONSTRAINT "PK_TNA" PRIMARY KEY (
	"TNA_DATE",
	"MEMBER_NAME"
);

ALTER TABLE "NOTE" ADD CONSTRAINT "PK_NOTE" PRIMARY KEY (
	"NOTE_SERIAL_NO"
);

ALTER TABLE "ELECTRONIC_APPROVAL" ADD CONSTRAINT "PK_ELECTRONIC_APPROVAL" PRIMARY KEY (
	"EA_SERIAL_NO"
);

ALTER TABLE "LEAVE_APPLICATION" ADD CONSTRAINT "PK_LEAVE_APPLICATION" PRIMARY KEY (
	"LA_SERIAL_NO"
);

ALTER TABLE "VOTE" ADD CONSTRAINT "PK_VOTE" PRIMARY KEY (
	"VOTE_SERIAL_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENTS_NO"
);

ALTER TABLE "ICECREAM" ADD CONSTRAINT "PK_ICE CREAM1" PRIMARY KEY (
	"ICE_NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"CO_SERIAL_NO"
);

ALTER TABLE "LA_APPROVAL_PATH" ADD CONSTRAINT "PK_LA_ APPROVAL_PATH" PRIMARY KEY (
	"LA_TURN",
	"LA_SERIAL_NO"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY (
	"DEPT_NO"
);

ALTER TABLE "RANK" ADD CONSTRAINT "PK_RANK" PRIMARY KEY (
	"RANK_NO"
);

ALTER TABLE "ADDENDUM" ADD CONSTRAINT "PK_ADDENDUM" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "EA_CARBON" ADD CONSTRAINT "PK_EA_CARBON" PRIMARY KEY (
	"EA_SERIAL_NO",
	"MEMBER_NAME"
);

ALTER TABLE "LA_ADDENDUM" ADD CONSTRAINT "PK_LA_ADDENDUM" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "DOCUMENT_FORM" ADD CONSTRAINT "PK_DOCUMENT_FORM" PRIMARY KEY (
	"DF_NO"
);

ALTER TABLE "VOTE_OPTION" ADD CONSTRAINT "PK_VOTE_OPTION" PRIMARY KEY (
	"VOTE_SERIAL_NO",
	"MEMBER_NAME"
);

ALTER TABLE "IN_OUT" ADD CONSTRAINT "PK_IN_OUT" PRIMARY KEY (
	"IN_OUT_NO"
);

ALTER TABLE "MEMBER_ROLE" ADD CONSTRAINT "PK_MEMBER_ROLE" PRIMARY KEY (
	"AUTHORITY_CODE",
	"MEMBER_NAME"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"AUTHORITY_CODE"
);

ALTER TABLE "AUTHENTICATED_MENU" ADD CONSTRAINT "PK_AUTHENTICATED_MENU" PRIMARY KEY (
	"AUTHORITY_CODE",
	"MENU_CODE"
);

ALTER TABLE "GLOBAL_MENU" ADD CONSTRAINT "PK_GLOBAL_MENU" PRIMARY KEY (
	"MENU_CODE"
);

ALTER TABLE "EA_APPROVAL_PATH" ADD CONSTRAINT "PK_EA_APPROVAL_PATH" PRIMARY KEY (
	"EA_NO",
	"EA_SERIAL_NO"
);

ALTER TABLE "VOTE_PARTICIPATION" ADD CONSTRAINT "PK_VOTE_PARTICIPATION" PRIMARY KEY (
	"VOTE_SERIAL_NO",
	"MEMBER_NAME"
);

ALTER TABLE "SP_MANAGEMENT" ADD CONSTRAINT "PK_SP_MANAGEMENT1" PRIMARY KEY (
	SP_NO
);

ALTER TABLE "SALARY" ADD CONSTRAINT "PK_SAL_SERIAL_NO" PRIMARY KEY (
	"SAL_SERIAL_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "INVENTORY" ADD CONSTRAINT "FK_ICECREAM_TO_INVENTORY_1" FOREIGN KEY (
	"ICE_NO"
)
REFERENCES "ICECREAM" (
	"ICE_NO"
);

ALTER TABLE "INVENTORY" ADD CONSTRAINT "FK_COMPANY_TO_INVENTORY_1" FOREIGN KEY (
	"CO_SERIAL_NO"
)
REFERENCES "COMPANY" (
	"CO_SERIAL_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_COMPANY_TO_MEMBER_1" FOREIGN KEY (
	"CO_SERIAL_NO"
)
REFERENCES "COMPANY" (
	"CO_SERIAL_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_DEPT_TO_MEMBER_1" FOREIGN KEY (
	"DEPT_NO"
)
REFERENCES "DEPT" (
	"DEPT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_RANK_TO_MEMBER_1" FOREIGN KEY (
	"RANK_NO"
)
REFERENCES "RANK" (
	"RANK_NO"
);

ALTER TABLE "TNA" ADD CONSTRAINT "FK_MEMBER_TO_TNA_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "NOTE" ADD CONSTRAINT "FK_MEMBER_TO_NOTE_1" FOREIGN KEY (
	"SENT_MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "NOTE" ADD CONSTRAINT "FK_MEMBER_TO_NOTE_2" FOREIGN KEY (
	"RECEIVE_MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "ELECTRONIC_APPROVAL" ADD CONSTRAINT "FK_MEM_TO_ELEC_APP_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "LEAVE_APPLICATION" ADD CONSTRAINT "FK_MEM_TO_LEAVE_APP_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "VOTE" ADD CONSTRAINT "FK_MEMBER_TO_VOTE_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"REF_COMMENTS_NO"
)
REFERENCES "COMMENTS" (
	"COMMENTS_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "LA_APPROVAL_PATH" ADD CONSTRAINT "FK_LEAVE_TO_APP_PATH_1" FOREIGN KEY (
	"LA_SERIAL_NO"
)
REFERENCES "LEAVE_APPLICATION" (
	"LA_SERIAL_NO"
);

ALTER TABLE "LA_APPROVAL_PATH" ADD CONSTRAINT "FK_MEM_TO_LA_ APP_PATH_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "ADDENDUM" ADD CONSTRAINT "FK_ADDENDUM_TO_ADDENDUM_1" FOREIGN KEY (
	"REF_COMMENT_NO"
)
REFERENCES "ADDENDUM" (
	"COMMENT_NO"
);

ALTER TABLE "ADDENDUM" ADD CONSTRAINT "FK_ELE_APP_TO_ADD_1" FOREIGN KEY (
	"EA_SERIAL_NO"
)
REFERENCES "ELECTRONIC_APPROVAL" (
	"EA_SERIAL_NO"
);

ALTER TABLE "ADDENDUM" ADD CONSTRAINT "FK_MEMBER_TO_ADDENDUM_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "EA_CARBON" ADD CONSTRAINT "FK_ELEC_APP_TO_EA_CARBON_1" FOREIGN KEY (
	"EA_SERIAL_NO"
)
REFERENCES "ELECTRONIC_APPROVAL" (
	"EA_SERIAL_NO"
);

ALTER TABLE "EA_CARBON" ADD CONSTRAINT "FK_MEMBER_TO_EA_CARBON_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "LA_ADDENDUM" ADD CONSTRAINT "FK_LA_ADD_TO_LA_ADD_1" FOREIGN KEY (
	"REF_COMMENT_NO"
)
REFERENCES "LA_ADDENDUM" (
	"COMMENT_NO"
);

ALTER TABLE "LA_ADDENDUM" ADD CONSTRAINT "FK_MEMBER_TO_LA_ADDENDUM_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "LA_ADDENDUM" ADD CONSTRAINT "FK_LEAVE_APP_TO_LA_ADDENDUM_1" FOREIGN KEY (
	"LA_SERIAL_NO"
)
REFERENCES "LEAVE_APPLICATION" (
	"LA_SERIAL_NO"
);

ALTER TABLE "VOTE_OPTION" ADD CONSTRAINT "FK_VOTE_TO_VOTE_OPTION_1" FOREIGN KEY (
	"VOTE_SERIAL_NO"
)
REFERENCES "VOTE" (
	"VOTE_SERIAL_NO"
);

ALTER TABLE "VOTE_OPTION" ADD CONSTRAINT "FK_MEMBER_TO_VOTE_OPTION_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "IN_OUT" ADD CONSTRAINT "FK_INVENTORY_TO_IN_OUT_1" FOREIGN KEY (
	"ICE_NO",
    "CO_SERIAL_NO"
)
REFERENCES "INVENTORY" (
	"ICE_NO",
    "CO_SERIAL_NO"
);

ALTER TABLE "MEMBER_ROLE" ADD CONSTRAINT "FK_AUTHORITY_TO_MEMBER_ROLE_1" FOREIGN KEY (
	"AUTHORITY_CODE"
)
REFERENCES "AUTHORITY" (
	"AUTHORITY_CODE"
);

ALTER TABLE "MEMBER_ROLE" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_ROLE_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "AUTHENTICATED_MENU" ADD CONSTRAINT "FK_AUTHORITY_TO_AUTH_MENU_1" FOREIGN KEY (
	"AUTHORITY_CODE"
)
REFERENCES "AUTHORITY" (
	"AUTHORITY_CODE"
);

ALTER TABLE "AUTHENTICATED_MENU" ADD CONSTRAINT "FK_GLOBAL_MENU_TO_AUTH_MENU_1" FOREIGN KEY (
	"MENU_CODE"
)
REFERENCES "GLOBAL_MENU" (
	"MENU_CODE"
);

ALTER TABLE "GLOBAL_MENU" ADD CONSTRAINT "FK_GLOB_ME_TO_GLOB_ME_1" FOREIGN KEY (
	"REF_MENU_CODE"
)
REFERENCES "GLOBAL_MENU" (
	"MENU_CODE"
);

ALTER TABLE "EA_APPROVAL_PATH" ADD CONSTRAINT "FK_ELECTRONIC_APP_TO_EA_APP_1" FOREIGN KEY (
	"EA_SERIAL_NO"
)
REFERENCES "ELECTRONIC_APPROVAL" (
	"EA_SERIAL_NO"
);

ALTER TABLE "EA_APPROVAL_PATH" ADD CONSTRAINT "FK_MEMBER_TO_EA_APP_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "VOTE_PARTICIPATION" ADD CONSTRAINT "FK_VOTE_TO_VOTE_PART_1" FOREIGN KEY (
	"VOTE_SERIAL_NO"
)
REFERENCES "VOTE" (
	"VOTE_SERIAL_NO"
);

ALTER TABLE "VOTE_PARTICIPATION" ADD CONSTRAINT "FK_MEMBER_TO_VOTE_PART_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "SP_MANAGEMENT" ADD CONSTRAINT "FK_MEMBER_TO_SP_MANAGEMENT_1" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

ALTER TABLE "SALARY" ADD CONSTRAINT "FK_MEMBER_TO_SALARY" FOREIGN KEY (
	"MEMBER_NAME"
)
REFERENCES "MEMBER" (
	"MEMBER_NAME"
);

-- ȸ�� ���̺� INSERT
INSERT
  INTO COMPANY
  (
    CO_SERIAL_NO
  , CO_DIVISION
  , CO_NAME
  , CO_STATUS
  )
  VALUES
  (
    SEQ_COMPANY_CODE.NEXTVAL
  , '����'
  , '����'
  , DEFAULT
  );
INSERT
  INTO COMPANY
  (
    CO_SERIAL_NO
  , CO_DIVISION
  , CO_NAME
  , CO_STATUS
  )
  VALUES
  (
    SEQ_COMPANY_CODE.NEXTVAL
  , '������'
  , '��������'
  , DEFAULT
  );
INSERT INTO COMPANY VALUES (SEQ_COMPANY_CODE.NEXTVAL, '������', '��ġ�꿪��', DEFAULT);
INSERT INTO COMPANY VALUES (SEQ_COMPANY_CODE.NEXTVAL, '������', '��ǿ���', DEFAULT);
INSERT INTO COMPANY VALUES (SEQ_COMPANY_CODE.NEXTVAL, '������', '��꿪��', DEFAULT);

-- ���� ���̺� INSERT
INSERT
  INTO RANK
  (
    RANK_NO
  , RANK_NAME
  )
  VALUES
  (
    SEQ_RANK_CODE.NEXTVAL
  , '����'
  );
INSERT
  INTO RANK
  (
    RANK_NO
  , RANK_NAME
  )
  VALUES
  (
    SEQ_RANK_CODE.NEXTVAL
  , '����'
  );
INSERT
  INTO RANK
  (
    RANK_NO
  , RANK_NAME
  )
  VALUES
  (
    SEQ_RANK_CODE.NEXTVAL
  , '����'
  );
INSERT
  INTO RANK
  (
    RANK_NO
  , RANK_NAME
  )
  VALUES
  (
    SEQ_RANK_CODE.NEXTVAL
  , '�븮'
  );
INSERT
  INTO RANK
  (
    RANK_NO
  , RANK_NAME
  )
  VALUES
  (
    SEQ_RANK_CODE.NEXTVAL
  , '���'
  );

-- �μ� ���̺� INSERT
INSERT
  INTO DEPT
  (
    DEPT_NO
  , DEPT_NAME
  )
  VALUES
  (
    SEQ_DEPT_CODE.NEXTVAL
  , '������'
  );
INSERT
  INTO DEPT
  (
    DEPT_NO
  , DEPT_NAME
  )
  VALUES
  (
    SEQ_DEPT_CODE.NEXTVAL
  , '�����ú�'
  );

-- ���� ���̺� INSERT
INSERT
  INTO MEMBER
  VALUES
  (
    '������', 1, 1, 1, '$2a$10$MkdT31pLLNHkZ7fUGmxzxekKMaUeCbVe2nwMSmDrXQSeyyp.0GNEi', 1676037393, 960420, '010-8905-7678', SYSDATE, SYSDATE, 3000000,
    600000, 42000000, 'grape420@naver.com', DEFAULT
  );
INSERT
  INTO MEMBER
  VALUES
  (
    '������', 2, 2, 2, '$2a$10$MkdT31pLLNHkZ7fUGmxzxekKMaUeCbVe2nwMSmDrXQSeyyp.0GNEi',1512345678, 930101, '010-1234-5678', SYSDATE, SYSDATE, 1000,
    500, 30000, 'jihyeakKing@naver.com', DEFAULT
  );
INSERT
  INTO MEMBER
  VALUES
  (
    '�谡��', 2, 2, 3, '$2a$10$MkdT31pLLNHkZ7fUGmxzxekKMaUeCbVe2nwMSmDrXQSeyyp.0GNEi',1543215678, 930101, '010-1234-5678', SYSDATE, SYSDATE, 1000,
    500, 30000, 'jihyeakKing@naver.com', DEFAULT
  );
INSERT
  INTO MEMBER
  VALUES
  (
    '��ȣ��', 2, 2, 4, '$2a$10$MkdT31pLLNHkZ7fUGmxzxekKMaUeCbVe2nwMSmDrXQSeyyp.0GNEi',1512345228, 930101, '010-1234-5678', SYSDATE, SYSDATE, 1000,
    500, 30000, 'jihyeakKing@naver.com', DEFAULT
  );
INSERT
  INTO MEMBER
  VALUES
  (
    '�輺��', 2, 2, 5, '$2a$10$MkdT31pLLNHkZ7fUGmxzxekKMaUeCbVe2nwMSmDrXQSeyyp.0GNEi',1812125678, 930101, '010-1234-5678', SYSDATE, SYSDATE, 1000,
    500, 30000, 'jihyeakKing@naver.com', DEFAULT
  );
  
-- ���� ���̺� INSERT
INSERT
  INTO AUTHORITY
  (
    AUTHORITY_CODE
  , AUTHORITY_NAME
  , AUTHORITY_DESC
  )
  VALUES
  (
    1
  , 'ROLE_MEMBER'
  , '�Ϲ�ȸ��'
  );
INSERT
  INTO AUTHORITY
  (
    AUTHORITY_CODE
  , AUTHORITY_NAME
  , AUTHORITY_DESC
  )
  VALUES
  (
    2
  , 'ROLE_ADMIN'
  , '������'
  );
  
-- ȸ�������� ���̺� INSERT
INSERT
  INTO MEMBER_ROLE
  (
    AUTHORITY_CODE
  , MEMBER_NAME
  )
  VALUES
  (
    1
  , '������'
  );
INSERT
  INTO MEMBER_ROLE
  (
    AUTHORITY_CODE
  , MEMBER_NAME
  )
  VALUES
  (
    1
  , '������'
  );
INSERT
  INTO MEMBER_ROLE
  (
    AUTHORITY_CODE
  , MEMBER_NAME
  )
  VALUES
  (
    2
  , '������'
  );
  
-- ���̽�ũ�� ���̺� INSERT
INSERT
  INTO "ICECREAM"
  (
    ICE_NO
  , ICE_NAME
  )
  VALUES
  (
    SEQ_ICECREAM_CODE.NEXTVAL
  , '�������� ��Ʈ�κ���'
  );
INSERT
  INTO "ICECREAM"
  (
    ICE_NO
  , ICE_NAME
  )
  VALUES
  (
    SEQ_ICECREAM_CODE.NEXTVAL
  , '�Ҷ�Ҷ� �ٴҶ�'
  );
INSERT
  INTO "ICECREAM"
  (
    ICE_NO
  , ICE_NAME
  )
  VALUES
  (
    SEQ_ICECREAM_CODE.NEXTVAL
  , '�ƺ��� �ܰ���'
  );
INSERT
  INTO "ICECREAM"
  (
    ICE_NO
  , ICE_NAME
  )
  VALUES
  (
    SEQ_ICECREAM_CODE.NEXTVAL
  , '��Ʈ��������'
  );
INSERT
  INTO "ICECREAM"
  (
    ICE_NO
  , ICE_NAME
  )
  VALUES
  (
    SEQ_ICECREAM_CODE.NEXTVAL
  , '��纣������'
  );
  
-- �Խ��� ���̺� INSERT
INSERT INTO BOARD VALUES(SEQ_BOARD_CODE.NEXTVAL, '������', '��������������˿�', SYSDATE,
                         '�����������', 0, 1);
INSERT INTO BOARD VALUES(SEQ_BOARD_CODE.NEXTVAL, '������', '��������������˿˿�', SYSDATE,
                         '�������������', 0, 2);
                         
-- ���� ���̺� INSERT
INSERT INTO NOTE VALUES(SEQ_NOTE_CODE.NEXTVAL, '������', '������', SYSDATE,
                         'Y', '�����������������');
INSERT INTO NOTE VALUES(SEQ_NOTE_CODE.NEXTVAL, '������', '������', SYSDATE,
                         'Y', '�����������������������');   
                         
-- ��� ���̺� INSERT
INSERT INTO "COMMENTS" VALUES(SEQ_COMMENT_CODE.NEXTVAL, SEQ_COMMENT_CODE.CURRVAL, 1, '������',
                         '���������������', SYSDATE, 1, 1, 'Y');
INSERT INTO "COMMENTS" VALUES(SEQ_COMMENT_CODE.NEXTVAL, SEQ_COMMENT_CODE.CURRVAL, 2, '������',
                         '���������������������', SYSDATE, 2, 1, 'Y');

-- ��ǥ ���̺� INSERT
INSERT INTO VOTE VALUES(SEQ_VOTE_CODE.NEXTVAL, '������', '�������������', '�������������',
                         1, SYSDATE, SYSDATE, 0);
INSERT INTO VOTE VALUES(SEQ_VOTE_CODE.NEXTVAL, '������', '���������������', '���������������',
                         2, SYSDATE, SYSDATE, 0);
                         
-- ��ǥ ������ ���̺� INSERT
INSERT INTO VOTE_OPTION VALUES(SEQ_VOTE_CODE.CURRVAL, '������', '�������������', 12);
INSERT INTO VOTE_OPTION VALUES(SEQ_VOTE_CODE.CURRVAL, '������', '�������������', 25);

-- ��ǥ ���� ���̺� INSERT
INSERT INTO VOTE_PARTICIPATION VALUES(SEQ_VOTE_CODE.CURRVAL, '������');
INSERT INTO VOTE_PARTICIPATION VALUES(SEQ_VOTE_CODE.CURRVAL, '������');

-- ���°��� ���̺� INSERT
INSERT INTO TNA VALUES(SYSDATE, '������', NULL);
INSERT INTO TNA VALUES(SYSDATE, '������', NULL);

-- ���� ��� ���̺� INSERT
INSERT INTO DOCUMENT_FORM VALUES(SEQ_DOCUMENT_CODE.NEXTVAL, '��ȼ�');
INSERT INTO DOCUMENT_FORM VALUES(SEQ_DOCUMENT_CODE.NEXTVAL, '�ް���');

-- ��� ���̺� INSERT
INSERT INTO INVENTORY VALUES(1, 1, 100);
INSERT INTO INVENTORY VALUES(2, 2, 200);
INSERT INTO INVENTORY VALUES(3, 3, 300);
INSERT INTO INVENTORY VALUES(4, 4, 400);
INSERT INTO INVENTORY VALUES(5, 5, 500);

-- ����� ���� ���̺� INSERT
INSERT INTO IN_OUT VALUES(SEQ_IN_OUT_CODE.NEXTVAL, 1, 1, SYSDATE, 1, 100);
INSERT INTO IN_OUT VALUES(SEQ_IN_OUT_CODE.NEXTVAL, 2, 2, SYSDATE, 2, 200);
INSERT INTO IN_OUT VALUES(SEQ_IN_OUT_CODE.NEXTVAL, 3, 3, SYSDATE, 3, 300);
INSERT INTO IN_OUT VALUES(SEQ_IN_OUT_CODE.NEXTVAL, 4, 4, SYSDATE, 1, 400);
INSERT INTO IN_OUT VALUES(SEQ_IN_OUT_CODE.NEXTVAL, 5, 5, SYSDATE, 2, 500);

-- ���� ���� (ELECTRONIC_APPROVAL) INSERT
INSERT INTO "ELECTRONIC_APPROVAL" VALUES(SEQ_EA_CODE.NEXTVAL, '������', SYSDATE, '��ȼ� ����1',
                         '���� ���� 1', 1, 1);
INSERT INTO "ELECTRONIC_APPROVAL" VALUES(SEQ_EA_CODE.NEXTVAL, '������', SYSDATE, '��ȼ� ����2',
                         '���� ���� 2', 2, 2);
INSERT INTO "ELECTRONIC_APPROVAL" VALUES(SEQ_EA_CODE.NEXTVAL, '������', SYSDATE, '��ȼ� ����3',
                         '���� ���� 3', 1, 3);      
                         
                         
-- ���� ���� ������ (EA_CARBON) INSERT
INSERT INTO "EA_CARBON" VALUES(SEQ_EA_CODE.CURRVAL, '������', 1);
                         
-- ���� ���� ÷�� (ADDENDUM) INSERT
INSERT INTO "ADDENDUM" VALUES(SEQ_ADDENDUM_CODE.NEXTVAL, SEQ_ADDENDUM_CODE.CURRVAL, SEQ_EA_CODE.CURRVAL, '������', '÷�� ���� 1', SYSDATE, 1, 1, 'Y');

-- ���� ���� ������� INSERT
INSERT INTO "EA_APPROVAL_PATH" VALUES(SEQ_EA_PATH_CODE.NEXTVAL, SEQ_EA_CODE.CURRVAL, '������', 1);

-- ������ ���� INSERT
INSERT INTO "SP_MANAGEMENT" VALUES (SEQ_SP_CODE.NEXTVAL,'������', 1000000000, 18);
INSERT INTO "SP_MANAGEMENT" VALUES (SEQ_SP_CODE.NEXTVAL,'������', 5000, 18);

-- �޿� ���� INSERT
INSERT INTO "SALARY" VALUES(SEQ_SALARY_CODE.NEXTVAL, '������', SYSDATE, '5000000', 2.0);
INSERT INTO "SALARY" VALUES(SEQ_SALARY_CODE.NEXTVAL, '������', SYSDATE, '50000', 0.5);

COMMIT;